[2025-04-24T14:48:53.897+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T14:48:53.906+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_lab.load_data_to_snowflake manual__2025-04-24T14:48:43.551339+00:00 [queued]>
[2025-04-24T14:48:53.911+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_lab.load_data_to_snowflake manual__2025-04-24T14:48:43.551339+00:00 [queued]>
[2025-04-24T14:48:53.911+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-24T14:48:53.917+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_data_to_snowflake> on 2025-04-24 14:48:43.551339+00:00
[2025-04-24T14:48:53.921+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=221) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-24T14:48:53.922+0000] {standard_task_runner.py:72} INFO - Started process 223 to run task
[2025-04-24T14:48:53.922+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '***_lab', 'load_data_to_snowflake', 'manual__2025-04-24T14:48:43.551339+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpdgovz4qg']
[2025-04-24T14:48:53.923+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask load_data_to_snowflake
[2025-04-24T14:48:53.949+0000] {task_command.py:467} INFO - Running <TaskInstance: airflow_lab.load_data_to_snowflake manual__2025-04-24T14:48:43.551339+00:00 [running]> on host 7ce975cba66d
[2025-04-24T14:48:53.995+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_lab' AIRFLOW_CTX_TASK_ID='load_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T14:48:43.551339+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T14:48:43.551339+00:00'
[2025-04-24T14:48:53.997+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T14:48:53.998+0000] {logging_mixin.py:190} INFO - No new data to load into Snowflake.
[2025-04-24T14:48:53.999+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-24T14:48:54.003+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T14:48:54.004+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=***_lab, task_id=load_data_to_snowflake, run_id=manual__2025-04-24T14:48:43.551339+00:00, execution_date=20250424T144843, start_date=20250424T144853, end_date=20250424T144854
[2025-04-24T14:48:54.020+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-24T14:48:54.029+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T14:48:54.030+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
