[2025-04-25T00:31:18.677+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-25T00:31:18.686+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_lab.load_data_to_snowflake manual__2025-04-25T00:31:08.446066+00:00 [queued]>
[2025-04-25T00:31:18.691+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_lab.load_data_to_snowflake manual__2025-04-25T00:31:08.446066+00:00 [queued]>
[2025-04-25T00:31:18.691+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-25T00:31:18.697+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_data_to_snowflake> on 2025-04-25 00:31:08.446066+00:00
[2025-04-25T00:31:18.701+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=493) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-25T00:31:18.702+0000] {standard_task_runner.py:72} INFO - Started process 495 to run task
[2025-04-25T00:31:18.703+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '***_lab', 'load_data_to_snowflake', 'manual__2025-04-25T00:31:08.446066+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpedfvskhi']
[2025-04-25T00:31:18.704+0000] {standard_task_runner.py:105} INFO - Job 180: Subtask load_data_to_snowflake
[2025-04-25T00:31:18.730+0000] {task_command.py:467} INFO - Running <TaskInstance: airflow_lab.load_data_to_snowflake manual__2025-04-25T00:31:08.446066+00:00 [running]> on host 3b98ce16fd30
[2025-04-25T00:31:18.774+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_lab' AIRFLOW_CTX_TASK_ID='load_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-25T00:31:08.446066+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-25T00:31:08.446066+00:00'
[2025-04-25T00:31:18.775+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-25T00:31:18.777+0000] {logging_mixin.py:190} INFO - No new data to load into Snowflake.
[2025-04-25T00:31:18.777+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-25T00:31:18.781+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-25T00:31:18.782+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=***_lab, task_id=load_data_to_snowflake, run_id=manual__2025-04-25T00:31:08.446066+00:00, execution_date=20250425T003108, start_date=20250425T003118, end_date=20250425T003118
[2025-04-25T00:31:18.801+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-25T00:31:18.810+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-25T00:31:18.810+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
